apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-app-deployment
  namespace: technical-test
  labels:
    app: version-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: version-app
  template:
    metadata:
      labels:
        app: version-app
    spec:
      containers:
      - name: version-app
        image: ghcr.io/venkatramachandran/version-app:latest
        resources: 
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 125Mi
        livenessProbe:
          httpGet:
            path: /version
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /version
            port: 3000
          initialDelaySeconds: 0
          timeoutSeconds: 1
        ports:
          - containerPort: 3000
