apiVersion: v1
kind: Service
metadata:
  name: version-app
  namespace: technical-test
spec:
  type: LoadBalancer
  selector:
    app: version-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000