name: Create Docker Image

on:
  release:
    types: [created]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Get short SHA
        id: gitsha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      -
        name: Set Docker Repo
        id: repo
        run: echo "::set-output name=repo::ghcr.io"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.repo.outputs.repo }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Run Docker Build
        id: docker_build
        run: docker build --build-arg gitsha=${{ steps.gitsha.outputs.sha8 }} -t ${{ steps.repo.outputs.repo }}/${{ github.repository }}:latest -t ${{ steps.repo.outputs.repo }}/${{ github.repository }}:${{ steps.gitsha.outputs.sha8 }} -t ${{ steps.repo.outputs.repo }}/${{ github.repository }}:${{ GITHUB_REF }} --file ./Dockerfile .
      -
        name: Scan Container
        id: scan_container
        uses: azure/container-scan@v0
        with:
          image-name: ${{ steps.repo.outputs.repo }}/${{ github.repository }}:${{ steps.gitsha.outputs.sha8 }}
      -
        name: Docker push
        id: docker_push
        run: for tag in latest ${{ GITHUB_REF }} ${{ steps.gitsha.outputs.sha8 }}; do docker push ${{ steps.repo.outputs.repo }}/${{ github.repository }}:$tag; done
